name: CI

on:

  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev zlib1g-dev

    - name: Download Dropbear 0.53.1
      run: |
        wget https://matt.ucc.asn.au/dropbear/releases/dropbear-0.53.1.tar.bz2
        tar -xjf dropbear-0.53.1.tar.bz2
        cd dropbear-0.53.1

    - name: Clone zlib
      run: git clone https://github.com/mkj/zlib.git

    - name: Build zlib
      run: |
        cd zlib
        ./configure --prefix=/usr/local/zlib
        make
        sudo make install

    - name: Configure Dropbear
      run: |
        cd dropbear-0.53.1
        export PATH=/usr/local/zlib/bin:$PATH
        ./configure --host=aarch64-unknown-linux-gnu --prefix=/usr/local/dropbear --with-zlib=/usr/local/zlib

    - name: Build Dropbear
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dropbear-0.53.1
        path: dropbear-0.53.1

    - name: Verify installation
      run: dbclient --version
