name: Build ARMv8 Dropbear for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK and NDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          mkdir -p $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;23.1.7779620"
          ls -R $ANDROID_HOME/ndk/23.1.7779620

      - name: Install dependencies
        run: |
          sudo apt-get install -y autoconf automake libtool make gcc g++ unzip wget

      - name: Download and extract Dropbear source
        run: |
          wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2022.83.tar.bz2
          tar -xf dropbear-2022.83.tar.bz2

      - name: Configure and build Dropbear
        run: |
          cd dropbear-2022.83
          export TOOLCHAIN=$ANDROID_HOME/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64
          export PATH=$TOOLCHAIN/bin:$PATH
          export AR=$TOOLCHAIN/bin/aarch64-linux-android-ar
          export AS=$TOOLCHAIN/bin/aarch64-linux-android-as
          export CC=$TOOLCHAIN/bin/aarch64-linux-android21-clang
          export CXX=$TOOLCHAIN/bin/aarch64-linux-android21-clang++
          export LD=$TOOLCHAIN/bin/aarch64-linux-android-ld
          export RANLIB=$TOOLCHAIN/bin/aarch64-linux-android-ranlib
          export STRIP=$TOOLCHAIN/bin/aarch64-linux-android-strip
          ls -R $TOOLCHAIN
          ./configure --host=aarch64-linux-android --enable-static || { cat config.log; exit 1; }
          make

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dropbear-android
          path: dropbear-2022.83/dropbear
