name: Build Dropbear for Android (64-bit)

on:
  push:
    branches:
      - main  # 在主分支推送时触发
  pull_request:
    branches:
      - main  # 在拉取请求提交到主分支时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2  # 检出当前代码仓库

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # 设置 JDK 11 环境

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make gcc g++ libssl-dev zlib1g-dev wget unzip

    - name: Install Android NDK
      run: |
        # 下载并解压 Android NDK
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip
        export ANDROID_NDK_HOME=$(pwd)/android-ndk-r21e
        echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r21e" >> $GITHUB_ENV  # 设置 NDK 环境变量

    - name: Download Dropbear source
      run: |
        # 克隆 Dropbear 源代码
        git clone https://github.com/mkj/dropbear.git
        cd dropbear
        git checkout master  # 选择需要的分支，或者使用指定的 commit

    - name: Build Dropbear for Android ARM64
      run: |
        cd dropbear
        make realclean  # 清理之前的构建文件
        # 使用 aarch64-linux-android 工具链，针对安卓64位架构进行编译
        make TARGET=android CROSS_COMPILE=aarch64-linux-android- NDK_ROOT=$ANDROID_NDK_HOME
        make install  # 安装编译好的文件

    - name: Archive the built Dropbear binaries
      uses: actions/upload-artifact@v2
      with:
        name: dropbear-binaries
        path: dropbear/dropbear  # 上传编译后的 Dropbear 二进制文件
