name: Build 64-bit Dropbear for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Android NDK
        with:
          ndk-version: '23.0.7599858'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool make gcc g++ unzip wget

      - name: Download and extract Dropbear source
        run: |
          wget https://matt.ucc.asn.au/dropbear/releases/dropbear-2022.83.tar.bz2
          tar -xf dropbear-2022.83.tar.bz2

      - name: Build Dropbear
        run: |
          cd dropbear-2022.83
          ./configure --host=aarch64-linux-android --enable-static
          make

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dropbear-android
          path: dropbear-2022.83/dropbear
