name: Build Android Dropbear

on:
  push:
    branches:
      - main # 或者你的默认分支
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Android SDK and NDK
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: '30' # 根据需要选择API级别
        arch: 'arm64-v8a' # 架构选择
        ndk-version: '27.2.12479018' # 选择一个稳定的NDK版本

    - name: Download latest Dropbear release
      run: |
        wget https://matt.ucc.asn.au/dropbear/releases/dropbear-latest.tar.bz2
        tar -jxvf dropbear-latest.tar.bz2
        cd $(find . -maxdepth 1 -type d -name "dropbear-*")
        pwd

    - name: Configure Dropbear for Android
      run: |
        cd $(find . -maxdepth 1 -type d -name "dropbear-*")
        ./configure --host=aarch64-linux-android --disable-zlib --disable-largefile --disable-loginfunc \
          --disable-shadow --disable-utmp --disable-wtmp --disable-lastlog CC=aarch64-linux-android21-clang \
          CXX=aarch64-linux-android21-clang++ STRIP=aarch64-linux-android-strip LDFLAGS=-static

    - name: Build Dropbear
      run: |
        cd $(find . -maxdepth 1 -type d -name "dropbear-*")
        make clean && make -j$(nproc)

    - name: Upload binaries as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dropbear-binaries
        path: |
          $(find . -maxdepth 2 -type d -name "dropbear-*")/dropbear
          $(find . -maxdepth 2 -type d -name "dropbear-*")/dropbearkey
          $(find . -maxdepth 2 -type d -name "dropbear-*")/dbclient
