name: Build Dropbear for Android (64-bit)

on:
  push:
    branches:
      - main  # 可以根据需要修改为你选择的分支
  pull_request:
    branches:
      - main  # 当有 pull request 提交到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make gcc g++ libssl-dev zlib1g-dev wget unzip

    - name: Install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip
        export ANDROID_NDK_HOME=$(pwd)/android-ndk-r21e
        echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r21e" >> $GITHUB_ENV

    - name: Download Dropbear source
      run: |
        git clone https://github.com/mkj/dropbear.git
        cd dropbear
        git checkout master  # 或者选择某个分支

    - name: Build Dropbear for Android ARM64
      run: |
        cd dropbear
        make realclean  # 清理之前的构建文件
        make TARGET=android CROSS_COMPILE=aarch64-linux-android- NDK_ROOT=$ANDROID_NDK_HOME  # 针对安卓64位架构(aarch64)
        make install  # 安装编译好的文件

    - name: Archive the built Dropbear binaries
      uses: actions/upload-artifact@v2
      with:
        name: dropbear-binaries
        path: dropbear/dropbear
